### ISSUE TITLE
请教寄存器配置问题

### ISSUE THREAD

**Issue by whenfhan** [Redns/sc_camera#1]
请问一下0x4418 和 0x4419 两个寄存器的作用是什么呢？为什么0x4418 和 0x4419 两个寄存器需要在 0x0100 写 0x01，且至少间隔 (2^17/mclk + 1) ms 之后再写入。

**Comment by Redns** [comment]
这两个寄存器的作用手册中没有指明，这里是按照 `SC031GS & SC035HGS 配置使用说明` 文档中的要求操作的，间隔时间示例如下

| MCLK(MHz) | TimeInterval(ms) |
|:------:|:-------:|
|27|6|
|24|7|
|12|12|
|6|23|
